spring: 
  redis: 
    database: 0
    host: www.springbootvuestudy.comcomcom
    port: 6379
    password: 123@456
    jedis: 
      pool: 
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0